/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as authSignInRouteRouteImport } from './routes/(auth)/sign-in/route'
import { Route as AppListingsIndexRouteImport } from './routes/_app/listings/index'
import { Route as AppCreateIndexRouteImport } from './routes/_app/create/index'
import { Route as AppCreateListingIdRouteImport } from './routes/_app/create/$listingId'
import { Route as authAppSignInRouteRouteImport } from './routes/(auth)/app/sign-in/route'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const authSignInRouteRoute = authSignInRouteRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppListingsIndexRoute = AppListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateIndexRoute = AppCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateListingIdRoute = AppCreateListingIdRouteImport.update({
  id: '/create/$listingId',
  path: '/create/$listingId',
  getParentRoute: () => AppRoute,
} as any)
const authAppSignInRouteRoute = authAppSignInRouteRouteImport.update({
  id: '/(auth)/app/sign-in',
  path: '/app/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof authSignInRouteRoute
  '/app/sign-in': typeof authAppSignInRouteRoute
  '/create/$listingId': typeof AppCreateListingIdRoute
  '/create/': typeof AppCreateIndexRoute
  '/listings/': typeof AppListingsIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRouteRoute
  '/': typeof AppIndexRoute
  '/app/sign-in': typeof authAppSignInRouteRoute
  '/create/$listingId': typeof AppCreateListingIdRoute
  '/create': typeof AppCreateIndexRoute
  '/listings': typeof AppListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRouteRoute
  '/_app/': typeof AppIndexRoute
  '/(auth)/app/sign-in': typeof authAppSignInRouteRoute
  '/_app/create/$listingId': typeof AppCreateListingIdRoute
  '/_app/create/': typeof AppCreateIndexRoute
  '/_app/listings/': typeof AppListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/app/sign-in'
    | '/create/$listingId'
    | '/create/'
    | '/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/app/sign-in'
    | '/create/$listingId'
    | '/create'
    | '/listings'
  id:
    | '__root__'
    | '/_app'
    | '/(auth)/sign-in'
    | '/_app/'
    | '/(auth)/app/sign-in'
    | '/_app/create/$listingId'
    | '/_app/create/'
    | '/_app/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  authSignInRouteRoute: typeof authSignInRouteRoute
  authAppSignInRouteRoute: typeof authAppSignInRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/listings/': {
      id: '/_app/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof AppListingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create/': {
      id: '/_app/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof AppCreateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/create/$listingId': {
      id: '/_app/create/$listingId'
      path: '/create/$listingId'
      fullPath: '/create/$listingId'
      preLoaderRoute: typeof AppCreateListingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/(auth)/app/sign-in': {
      id: '/(auth)/app/sign-in'
      path: '/app/sign-in'
      fullPath: '/app/sign-in'
      preLoaderRoute: typeof authAppSignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCreateListingIdRoute: typeof AppCreateListingIdRoute
  AppCreateIndexRoute: typeof AppCreateIndexRoute
  AppListingsIndexRoute: typeof AppListingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCreateListingIdRoute: AppCreateListingIdRoute,
  AppCreateIndexRoute: AppCreateIndexRoute,
  AppListingsIndexRoute: AppListingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  authSignInRouteRoute: authSignInRouteRoute,
  authAppSignInRouteRoute: authAppSignInRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
