/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as authSignInRouteRouteImport } from './routes/(auth)/sign-in/route'
import { Route as authAppSignInRouteRouteImport } from './routes/(auth)/app/sign-in/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRouteRoute = authSignInRouteRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authAppSignInRouteRoute = authAppSignInRouteRouteImport.update({
  id: '/(auth)/app/sign-in',
  path: '/app/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRouteRoute
  '/create/': typeof CreateIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/app/sign-in': typeof authAppSignInRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRouteRoute
  '/create': typeof CreateIndexRoute
  '/listings': typeof ListingsIndexRoute
  '/app/sign-in': typeof authAppSignInRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/sign-in': typeof authSignInRouteRoute
  '/create/': typeof CreateIndexRoute
  '/listings/': typeof ListingsIndexRoute
  '/(auth)/app/sign-in': typeof authAppSignInRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/create/' | '/listings/' | '/app/sign-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/create' | '/listings' | '/app/sign-in'
  id:
    | '__root__'
    | '/'
    | '/(auth)/sign-in'
    | '/create/'
    | '/listings/'
    | '/(auth)/app/sign-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authSignInRouteRoute: typeof authSignInRouteRoute
  CreateIndexRoute: typeof CreateIndexRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  authAppSignInRouteRoute: typeof authAppSignInRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/app/sign-in': {
      id: '/(auth)/app/sign-in'
      path: '/app/sign-in'
      fullPath: '/app/sign-in'
      preLoaderRoute: typeof authAppSignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authSignInRouteRoute: authSignInRouteRoute,
  CreateIndexRoute: CreateIndexRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  authAppSignInRouteRoute: authAppSignInRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
